#!/usr/bin/env bash
#root=$(git rev-parse --show-toplevel)
#files=($(git diff --name-only --cached | egrep '\.php$' | sed -e "s|^|$root/|"))
#for file in "${files[@]}"; do
#    if [ -f "$file" ]; then
#        php -l "$file" > /dev/null
#        if [ $? -ne 0 ]; then
#            exit 1
#        fi
#    fi
#done
