#!/usr/bin/env bash

#dir=$(cd $(dirname $0);pwd)
#
## Check php syntax
#$dir/check-php-syntax
#if [ $? -ne 0 ]; then
#    message="Aborting commit due to files with syntax errors."
#    echo -e "\033[0;31m$message\033[0;39m" >&2
#    exit 1
#fi

## Run php-cs-fixer
#$dir/run-php-cs-fixer
#if [ $? -ne 0 ]; then
#    exit 1
#fi

# ブランチがmasterならば
branch="$(git symbolic-ref HEAD 2>/dev/null)" || "$(git describe --contains --all HEAD)"
if [ "${branch##refs/heads/}" = "master" ]; then
	# コミット履歴があるならばmasterへのCommitはfail
	# コミット履歴がないならばmasterへのFirst Commitだけは許す
	git rev-list --max-parents=0 HEAD > /dev/null 2>&1
	if [ "$?" = "0" ]; then
		echo "Do not commit on the master branch!"
		exit 1
	fi
fi
